### ISSUE TITLE
[cli] provider create command returns nothing on success

### ISSUE THREAD

**Issue by markusheiliger** [microsoft/TeamCloud#133]
**Describe the bug**
The command `az tc provider create --url http://localhost:7101 --name azure.appinsights --auth-code xxxxxx` returns nothing on success. This is an inconsistent behavior as e.g. the command `az tc project-type create -n project.standard --provider azure.appinsights --provider azure.devtestlabs --subscriptions 929097d0-4c3c-47d7-b59e-e5e609f1d71f --resource-group-name-prefix TC_DEV_STANDARD_ -l EastUS --default` returns the json representation of the created entity.

**To Reproduce**
Run the command

**Expected behavior**
Returns the created entity as JSON.

**Additional context**
n/a

**Comment by colbylwilliams** [comment]
@markusheiliger I think this was fixed when you fixed the issue in the orchestrator where deploying providers never finished.

**Comment by markusheiliger** [comment]
@colbylwilliams we need to talk about this. it looks like the final cli call (processing completed) is rejected by the api => unauthorized

![image](https://user-images.githubusercontent.com/12153683/91072900-11650900-e5ef-11ea-9f87-4452f05a2392.png)
