### ISSUE TITLE
Ensure serialized DateTimes on documents/model conform to the Iso8601Literal format

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#152]
See the [doc](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1131-the-dateliteral-format).
> A string literal as defined in https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15. Note that the full grammar for ISO 8601 (such as "basic format" without separators) is not supported.
> All dates default to UTC unless specified otherwise.

**Comment by markusheiliger** [comment]
closed because of solution redesign
