### ISSUE TITLE
Add List API to the Status endpoint (with filtering query params)

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#154]
[doc](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1325-operation-resource)
[retention policy for operation results](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#133-retention-policy-for-operation-results)

**Comment by markusheiliger** [comment]
closed because of solution redesign
