### ISSUE TITLE
Web UI shows project even if not yet fully provisioned

### ISSUE THREAD

**Issue by markusheiliger** [microsoft/TeamCloud#192]
**Describe the bug**
Projects are listed and available through the UI (didn't check the CLI) for operations even if the creation wasn't finished. This could lead to a situation where the users want's to start modifying the project (e.g. adding users) even if the project creation ends in a rollback. We should introduce a state indicator for a project that gives the clients the opportunity to handle these constellations properly. 

**To Reproduce**
Hard to reproduce - need to force an error on the provider side, so the orchestrator initiates a project rollback.

**Expected behavior**
Project isn't shown until the creation process is successfully finished, or the project is available on the client side but locked while creation is in progress.

**Comment by markusheiliger** [comment]
@colbylwilliams we should discuss this in our next standup

**Comment by colbylwilliams** [comment]
Yeah, as soon as it's in the DB, the API is gonna return it.  I like the idea of a state property on the project so we can still show something in the UI when it's "creating" or "provisioning" but block actions on it until it's "active".

We could use it in the future too for states like "locked", "archived", etc.

**Comment by markusheiliger** [comment]
closed because of solution redesign
