### ISSUE TITLE
Prevent deploying web app to same resource group as TeamCloud instance.

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#193]
Per the [docs](https://docs.microsoft.com/en-us/azure/app-service/overview#limitations), you can't mix Windows and Linux apps in the same App Service plan.  This means attempting to deploy the web app to the same resource group as the TeamCloud instance will always fail.  We should prevent this.

**Comment by markusheiliger** [comment]
closed because of solution redesign
