### ISSUE TITLE
Azure AD groups for project members

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/TeamCloud#224]
**Is your feature request related to a problem? Please describe.**
At my employer we provision projects around sets of groups and access to resources with these same groups. Every project/team gets an Administrator, Contributor and Reader role. These roles more or less exactly relate to azure devops and azure RBAC roles of the same name. There might be other roles if more specific RBAC is needed by the project but every project gets at least those basic roles. I couldn't find any mention of this in the docs so I assume it's not yet supported.

**Describe the solution you'd like**
Create azure AD groups when a new project is created. Users added to the project will be added to the azure ad group(s)

**Describe alternatives you've considered**
Since there doesn't appear to be any RBAC yet, we could start with just one group per project. Ideally of course we would like to have full RBAC support.

**Comment by markusheiliger** [comment]
closed because of solution redesign
