### ISSUE TITLE
Basic 3 tiered RBAC

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/TeamCloud#225]
**Is your feature request related to a problem? Please describe.**
Most relevant resources like azure, azure devops, github support at least the basic RBAC of Administrator (or owner), contributor, reader. It would be great to support that on a team level.

**Describe the solution you'd like**
Ability to give team members a role. This role would also be set in every resource associated with the project.

**Comment by markusheiliger** [comment]
closed because of solution redesign
