### ISSUE TITLE
Per-project resource allowance

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/TeamCloud#226]
**Is your feature request related to a problem? Please describe.**
It is unclear to me from the documentation whether or not all resource providers are always activated for all projects.

Especially this line makes it seem like all providers are active for all projects:

"For example, an organization may implement an "Azure Key Vault Provider" responsible for creating a new Key Vault instance for each Project."

It would be nice to be able to select per-project which providers will be active for them, and also which would be activated on project creation and which can be manually activated by the team on a self-serve basis.

**Describe the solution you'd like**
I would like to decide on a per-project basis if they have permission to use a provider. For example a Java project might like to use gitlab and not azure devops, so having the azure devops provider available would only be clutter.

It would also be nice to be able to say ''this project can have one of or three of provider x'.

Apologies if this feature is already there, I'll also deploy a TeamCloud instance and check myself. If I find that it's possible I'll close this issue.

**Comment by markusheiliger** [comment]
closed because of solution redesign
