### ISSUE TITLE
Create WEB UI app registration from az deploy command

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/TeamCloud#229]
**Is your feature request related to a problem? Please describe.**
The current instructions tell you to create the web ui app registration manually for the webui. The app registration for the backend is created automatically upon deployment. This can be done for the webui as well.

**Describe the solution you'd like**
Create the app registration for the web ui as part of the web ui deployment instead of directing users to create it manually.

**Comment by markusheiliger** [comment]
closed because of solution redesign
