### ISSUE TITLE
Getting 404 on installing the az extension

### ISSUE THREAD

**Issue by henrikmotzkus** [microsoft/TeamCloud#290]
**Describe the bug**
Getting 404 on installing the az extension from documentation

**To Reproduce**
Tried to install accordingly to the documentation

az extension add --source https://github.com/microsoft/TeamCloud/releases/latest/download/tc-0.4.1-py2.py3-none-any.whl -y

Request to https://github.com/microsoft/TeamCloud/releases/latest/download/tc-0.4.1-py2.py3-none-any.whl failed with 404

**Expected behavior**
Assume documentation is not accurate.

**Additional context**

**Comment by colbylwilliams** [comment]
sorry for the broken link, readme is updated with the correct path
