### ISSUE TITLE
Validate Project Names are unique for new Projects

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#31]
When the user tries to create a new project, check the DB for an existing project with that name, if there's already a project in the DB with that name, return an error.

**Comment by colbylwilliams** [comment]
@madenwala Can you address the following:
1. `NameExistsAsync` should be on `IProjectsRepositoryReadOnly` not on `IProjectsRepository` as it is a read operation
2. The `ProjectsController` and the API in general cannot perform write operations, only read, so please revert the `ProjectsController` constructor to take a `IProjectsRepositoryReadOnly` param
3. Since we're checking if the name is unique the `ProjectsController` (so we can return a useful error to the user), I don't think it makes sense to check again in the `ProjectCreateActivity`

**Comment by colbylwilliams** [comment]
@madenwala I went ahead and made the changes in 932099458a2c7619a9e2d34cc568c7d4e50aa29f and e9f27bb550aacb7c641ea47694925bb28218b619

**Comment by colbylwilliams** [comment]
Change the `ProjectController` to return Conflict if the name exists vs BadRequest 7480b00f47e1596b6b29382ab3297b041caf9540

**Comment by madenwala** [comment]
@colbylwilliams we good with closing this issue?
