### ISSUE TITLE
TeamCloud website cannot allow to login

### ISSUE THREAD

**Issue by luxu-ms** [microsoft/TeamCloud#332]
**Describe the bug**
According to the documentation, I have registered the AppConfiguration and SignalRService and successfully deploy the TeamCloud instance. However, when I access the TeamCloud website, it doesn't allow to login.
The error is as below:
![image](https://user-images.githubusercontent.com/92287281/165419614-fe08078c-bba3-40bd-bf75-086a219177f7.png)

looks like there is no permission as admin.

**To Reproduce**
1, in App Registration part, input the "api://<GUID>" as the application ID URI
2, pass the scope during the deployment az tc deploy --scope "api://<GUID>/user_impersonation"
3，access the TeamCloud website "https://teamcloudapp2dev.azurewebsites.net"
Actual result: The error above will be displayed.

**Expected behavior**
The page should allow me to login

**Additional context**

**Comment by rouke-broersma** [comment]
This is something you need to take up with your directory (tenant) admin. Your tenant has restricted users from granting the necessary permissions to aad apps, so your admin has to grant the approval. This is not an issue in TeamCloud.

**Comment by luxu-ms** [comment]
> This is something you need to take up with your directory (tenant) admin. Your tenant has restricted users from granting the necessary permissions to aad apps, so your admin has to grant the approval. This is not an issue in TeamCloud.

Thanks for the reply.
Some customers may have the same permission as mine. Or they have even more restricted rules. So they need to ask tenant admin to approve for Team Cloud try? Any workaround?

**Comment by rouke-broersma** [comment]
Yes, you can use another tenant that does not have these restrictions.

**Comment by luxu-ms** [comment]
> Yes, you can use another tenant that does not have these restrictions.

Thanks Rouke. Now I change to another limited cash subscription. The issue is resolved. However, I found that subscription cannot be input and subscription list is empty, is there any idea to solve this? I will create another thread to address this new issue.

**Comment by colbylwilliams** [comment]
@luxu-ms similar to my comment in issue #334, the TeamCloud's service principal needs contributor permissions on the subscription.  Let me know if that fixes this issue.

**Comment by colbylwilliams** [comment]
Tracking the related documentation update task in issue #336.

_For MSFT employees that stumble across this issue, TeamCloud instances do not currently work within the Microsoft tenant due to restrictions to constraints on permissions that can be granted to a service principal._

Closing.
