### ISSUE TITLE
Delete command results should not have location links

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#67]
In TeamCloud.API/Services/Orchestrator SetResultLinks we shouldn't set a value for `location` in the `Links` dictionary **if the command was a delete command** because we use the presence of the `location` key to set the `Location` header of the API response.  If there's a `Location` header clients will to that location, which in turn results in a 404 (because the resource was successfully deleted).

As a rule **any command that deletes a resource should not have a `location` link**  TeamCloud.API/Services/Orchestrator needs to be updated to resolve this, otherwise delete api calls will always end in 404 error

**Comment by markusheiliger** [comment]
Isn't the location link in this case pointing to the operation status url? if this is true, we don't need to change anything as even a delete is an operation you maybe want to wait for. and in this case the status url is absolutely useful.

**Comment by colbylwilliams** [comment]
No, the `status` key in the Links retains the url of the status.  The `location` key is only used for create and update commands allowing the client to redirect (302) to the actual resource that was created or updated upon command completion, while leaving the status url to query the command result later.  But delete commands don't have a resource (204) to point to (because it was deleted).
