### ISSUE TITLE
Project Create Orchestration

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/TeamCloud#8]
[ProjectCreateOrchestration](https://github.com/microsoft/TeamCloud/blob/master/src/TeamCloud.Orchestrator/Orchestrations/ProjectCreateOrchestration.cs)

1. Create a new project and save to the database (via activity functions)
2. Create an Azure resource group for the project (and update project in db)
3. Invoke the Create command on each Provider (accounting for dependencies)
4. Wait for Create commands to complete, then invoke the Init Command on each Provider (accounting for dependencies)

**Comment by madenwala** [comment]
1 and 2 are complete.
