### ISSUE TITLE
[cli] Validation issue on "az tc project-type create"

### ISSUE THREAD

**Issue by markusheiliger** [microsoft/TeamCloud#87]
**Describe the bug**
Reported error: --name should start with a lowercase and contain only lowercase, numbers, and periods [.] with length [5,254]

**To Reproduce**
az tc project-type create --name default --subscriptions [guid] --provider azure.appinsights --provider azure.devops --provider azure.devtestlab --location EastUS --resource-group-name-prefix tcmarkus_ --default

**Comment by markusheiliger** [comment]
it looks like the issue is related to a missing period in the project type name. Changing the project type name to default.project solved the validation issue in my case.

**Comment by colbylwilliams** [comment]
Fixed in [v0.3.0](https://www.myget.org/feed/teamcloud-dev/package/pythonwhl/tc).  Please [update](https://github.com/microsoft/TeamCloud/blob/master/docs/CLI.md#update).
