### ISSUE TITLE
[cli] az tc project-type create requires (at least) 3 subscription Ids

### ISSUE THREAD

**Issue by markusheiliger** [microsoft/TeamCloud#88]
**Describe the bug**
Returned validation error: --subscriptions should be a space-separated list of at least 3 valid uuids

**To Reproduce**
az tc project-type create --name default.project --subscriptions [guid] --provider azure.appinsights --provider azure.devops --provider azure.devtestlab --location EastUS --resource-group-name-prefix tcmarkus_ --default

**Additional context**
Why do we need a min number of subscription Ids anyway? One should be enough IMO? Especially as using the same subscription Id 3 times as the parameter value solves the issue. So, the subscription Ids are not even checked for uniqueness.

**Comment by colbylwilliams** [comment]
Fixed in [v0.3.0](https://www.myget.org/feed/teamcloud-dev/package/pythonwhl/tc).  Please [update](https://github.com/microsoft/TeamCloud/blob/master/docs/CLI.md#update).
