### ISSUE TITLE
[cli] validation error on: az tc project-type create

### ISSUE THREAD

**Issue by markusheiliger** [microsoft/TeamCloud#90]
**Describe the bug**
CLI returns a validation error for 'region' (must not be empty), but the location param of the command is optional

`{
  "code": 400,
  "errors": [
    {
      "code": "ValidationError",
      "errors": [
        {
          "field": "region",
          "message": "'region' must not be empty."
        }
      ],
      "message": "Validation Failed"
    }
  ],
  "status": "BadRequest"
}`

**To Reproduce**
az tc project-type create -n project.simple --provider azure.appinsights --provider azure.devops --provider azure.devtestlabs --subscriptions [guid] --default --resource-group-name-prefix TC_

**Comment by colbylwilliams** [comment]
@markusheiliger is region a requirement for new project types?  If so, I'll make it a requirement in the CLI, if not (we have some way to fallback in the API/Orchestrator code), I'll update the Model Validation to allow null for ProjectType.Region.

**Comment by colbylwilliams** [comment]
Fixed in v0.3.1 please [update](https://github.com/microsoft/TeamCloud/blob/master/docs/CLI.md#update) to the latest version.
